[package]
name = "node-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
primitives = { package = "sp-core", git = "https://github.com/ProChain/substrate.git", default-features = false }
sp-runtime = { git = "https://github.com/ProChain/substrate.git", default-features = false }

[dev-dependencies]
sp-serializer = { git = "https://github.com/ProChain/substrate.git" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"primitives/std",
	"sp-runtime/std",
]
