[package]
name = "node-cli"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
build = "build.rs"
edition = "2018"
default-run = "prochain"

[badges]
travis-ci = { repository = "paritytech/substrate", branch = "master" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[[bin]]
name = "prochain"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6" }
serde = { version = "1.0.102", features = ["derive"] }
futures01 = { package = "futures", version = "0.1.29" }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "14.0.3"
log = "0.4.8"
rand = "0.7.2"
structopt = "0.3.3"
serde_json = "1.0.41"
hex = "0.4.0"

# primitives
authority-discovery-primitives = { package = "sp-authority-discovery", git = "https://github.com/ProChain/substrate.git"}
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/ProChain/substrate.git" }
grandpa_primitives = { package = "sp-finality-grandpa", git = "https://github.com/ProChain/substrate.git" }
primitives = { package = "sp-core", git = "https://github.com/ProChain/substrate.git" }
sp-runtime = { git = "https://github.com/ProChain/substrate.git" }
sp-timestamp = { git = "https://github.com/ProChain/substrate.git", default-features = false }
sp-finality-tracker = { git = "https://github.com/ProChain/substrate.git", default-features = false }
inherents = { package = "sp-inherents", git = "https://github.com/ProChain/substrate.git" }
keyring = { package = "sp-keyring", git = "https://github.com/ProChain/substrate.git" }
runtime-io = { package = "sp-io", git = "https://github.com/ProChain/substrate.git" }
consensus-common = { package = "sp-consensus", git = "https://github.com/ProChain/substrate.git"}

# client dependencies
client-api = { package = "sc-client-api", git = "https://github.com/ProChain/substrate.git" }
client = { package = "sc-client", git = "https://github.com/ProChain/substrate.git" }
chain-spec = { package = "sc-chain-spec", git = "https://github.com/ProChain/substrate.git" }
txpool = { package = "sc-transaction-pool", git = "https://github.com/ProChain/substrate.git" }
txpool-api = { package = "sp-transaction-pool-api", git = "https://github.com/ProChain/substrate.git" }
network = { package = "sc-network", git = "https://github.com/ProChain/substrate.git" }
babe = { package = "sc-consensus-babe", git = "https://github.com/ProChain/substrate.git" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/ProChain/substrate.git" }
client-db = { package = "sc-client-db", git = "https://github.com/ProChain/substrate.git", default-features = false }
offchain = { package = "sc-offchain", git = "https://github.com/ProChain/substrate.git" }
sc-rpc = { git = "https://github.com/ProChain/substrate.git" }
sc-basic-authority = { git = "https://github.com/ProChain/substrate.git" }
sc-service = { git = "https://github.com/ProChain/substrate.git", default-features = false }
sc-telemetry = { git = "https://github.com/ProChain/substrate.git" }
authority-discovery = { package = "sc-authority-discovery", git = "https://github.com/ProChain/substrate.git"}

# frame dependencies
indices = { package = "pallet-indices", git = "https://github.com/ProChain/substrate.git" }
timestamp = { package = "pallet-timestamp", git = "https://github.com/ProChain/substrate.git", default-features = false }
contracts = { package = "pallet-contracts", git = "https://github.com/ProChain/substrate.git" }
system = { package = "frame-system", git = "https://github.com/ProChain/substrate.git" }
balances = { package = "pallet-balances", git = "https://github.com/ProChain/substrate.git" }
transaction-payment = { package = "pallet-transaction-payment", git = "https://github.com/ProChain/substrate.git" }
support = { package = "frame-support", git = "https://github.com/ProChain/substrate.git", default-features = false }
im_online = { package = "pallet-im-online", git = "https://github.com/ProChain/substrate.git", default-features = false }
sr-authority-discovery = { package = "pallet-authority-discovery", git = "https://github.com/ProChain/substrate.git"}

# node-specific dependencies
node-runtime = { path = "../runtime" }
node-rpc = { path = "../rpc" }
node-primitives = { path = "../primitives" }
node-executor = { path = "../executor" }

# CLI-specific dependencies
tokio = { version = "0.1.22", optional = true }
sc-cli = { git = "https://github.com/ProChain/substrate.git", optional = true }
transaction-factory = { path = "../../../test/utils/transaction-factory", optional = true }
ctrlc = { version = "3.1.3", features = ["termination"], optional = true }

# WASM-specific dependencies
libp2p = { version = "0.13.0", default-features = false, optional = true }
clear_on_drop = { version = "0.2.3", features = ["no_cc"], optional = true }	# Imported just for the `no_cc` feature
console_error_panic_hook = { version = "0.1.1", optional = true }
console_log = { version = "0.1.2", optional = true }
js-sys = { version = "0.3.22", optional = true }
wasm-bindgen = { version = "0.2.45", optional = true }
wasm-bindgen-futures = { version = "0.3.22", optional = true }
kvdb-memorydb = { version = "0.1.1", optional = true }
rand6 = { package = "rand", version = "0.6", features = ["wasm-bindgen"], optional = true }	# Imported just for the `wasm-bindgen` feature

[dev-dependencies]
keystore = { package = "sc-keystore", git = "https://github.com/ProChain/substrate.git" }
babe = { package = "sc-consensus-babe", git = "https://github.com/ProChain/substrate.git", features = ["test-helpers"] }
service-test = { package = "sc-service-test", git = "https://github.com/ProChain/substrate.git" }
futures = "0.3.1"
tempfile = "3.1.0"

[build-dependencies]
sc-cli = { package = "sc-cli", git = "https://github.com/ProChain/substrate.git" }
build-script-utils = { package = "substrate-build-script-utils", path = "../../../utils/build-script-utils" }
structopt = "0.3.3"
vergen = "3.0.4"

[features]
default = ["cli"]
browser = [
	"clear_on_drop",
	"console_error_panic_hook",
	"console_log",
	"js-sys",
	"libp2p",
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"kvdb-memorydb",
	"rand/wasm-bindgen",
	"rand6"
]
cli = [
	"sc-cli",
	"transaction-factory",
	"tokio",
	"ctrlc",
	"sc-service/rocksdb",
	"node-executor/wasmi-errno",
]
wasmtime = [
	"cli",
	"node-executor/wasmtime",
	"sc-cli/wasmtime",
	"sc-service/wasmtime",
]
