[package]
name = "node-runtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.103", features = ["derive"], optional = true }
simple-json = { version = '0.1.1', git = "https://github.com/jingleizhang/simple-json.git", default-features = false }
hex = { version = "0.4.0", default-features = false }

# primitives
authority-discovery-primitives = { package = "sp-authority-discovery", git = "https://github.com/ProChain/substrate.git", default-features = false }
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/ProChain/substrate.git", default-features = false }
block-builder-api = { package = "sp-block-builder", git = "https://github.com/ProChain/substrate.git", default-features = false}
inherents = { package = "sp-inherents", git = "https://github.com/ProChain/substrate.git", default-features = false }
node-primitives = { path = "../primitives", default-features = false }
offchain-primitives = { package = "sp-offchain", git = "https://github.com/ProChain/substrate.git", default-features = false }
primitives = { package = "sp-core",  git = "https://github.com/ProChain/substrate.git", default-features = false }
rstd = { package = "sp-std", git = "https://github.com/ProChain/substrate.git", default-features = false }
sp-api = { git = "https://github.com/ProChain/substrate.git", default-features = false }
sp-runtime = { git = "https://github.com/ProChain/substrate.git", default-features = false }
sp-staking = { git = "https://github.com/ProChain/substrate.git", default-features = false }
sp-keyring = { git = "https://github.com/ProChain/substrate.git", optional = true }
sp-session = { git = "https://github.com/ProChain/substrate.git", default-features = false }
sp-transaction-pool = { package = "sp-transaction-pool-api", git = "https://github.com/ProChain/substrate.git", default-features = false }
version = { package = "sp-version", git = "https://github.com/ProChain/substrate.git", default-features = false }

# frame dependencies
authority-discovery = { package = "pallet-authority-discovery", git = "https://github.com/ProChain/substrate.git", default-features = false }
authorship = { package = "pallet-authorship", git = "https://github.com/ProChain/substrate.git", default-features = false }
babe = { package = "pallet-babe", git = "https://github.com/ProChain/substrate.git", default-features = false }
balances = { package = "pallet-balances", git = "https://github.com/ProChain/substrate.git", default-features = false }
collective = { package = "pallet-collective", git = "https://github.com/ProChain/substrate.git", default-features = false }
contracts = { package = "pallet-contracts", git = "https://github.com/ProChain/substrate.git", default-features = false }
contracts-rpc-runtime-api = { package = "pallet-contracts-rpc-runtime-api", git = "https://github.com/ProChain/substrate.git", default-features = false }
democracy = { package = "pallet-democracy", git = "https://github.com/ProChain/substrate.git", default-features = false }
elections-phragmen = { package = "pallet-elections-phragmen", git = "https://github.com/ProChain/substrate.git", default-features = false }
executive = { package = "frame-executive", git = "https://github.com/ProChain/substrate.git", default-features = false }
finality-tracker = { package = "pallet-finality-tracker", git = "https://github.com/ProChain/substrate.git", default-features = false }
grandpa = { package = "pallet-grandpa", git = "https://github.com/ProChain/substrate.git", default-features = false }
im-online = { package = "pallet-im-online", git = "https://github.com/ProChain/substrate.git", default-features = false }
indices = { package = "pallet-indices", git = "https://github.com/ProChain/substrate.git", default-features = false }
membership = { package = "pallet-membership", git = "https://github.com/ProChain/substrate.git", default-features = false }
nicks = { package = "pallet-nicks", git = "https://github.com/ProChain/substrate.git", default-features = false }
offences = { package = "pallet-offences", git = "https://github.com/ProChain/substrate.git", default-features = false }
randomness-collective-flip = { package = "pallet-randomness-collective-flip", git = "https://github.com/ProChain/substrate.git", default-features = false }
session = { package = "pallet-session", git = "https://github.com/ProChain/substrate.git", default-features = false, features = ["historical"] }
staking = { package = "pallet-staking", git = "https://github.com/ProChain/substrate.git", default-features = false, features = ["migrate"] }
pallet-staking-reward-curve = { git = "https://github.com/ProChain/substrate.git"}
sudo = { package = "pallet-sudo", git = "https://github.com/ProChain/substrate.git", default-features = false }
support = { package = "frame-support", git = "https://github.com/ProChain/substrate.git", default-features = false }
system = { package = "frame-system", git = "https://github.com/ProChain/substrate.git", default-features = false }
system-rpc-runtime-api = { package = "frame-system-rpc-runtime-api", git = "https://github.com/ProChain/substrate.git", default-features = false }
timestamp = { package = "pallet-timestamp", git = "https://github.com/ProChain/substrate.git", default-features = false }
treasury = { package = "pallet-treasury", git = "https://github.com/ProChain/substrate.git", default-features = false }
utility = { package = "frame-utility", git = "https://github.com/ProChain/substrate.git", default-features = false }
transaction-payment = { package = "pallet-transaction-payment", git = "https://github.com/ProChain/substrate.git", default-features = false }
transaction-payment-rpc-runtime-api = { package = "pallet-transaction-payment-rpc-runtime-api", git = "https://github.com/ProChain/substrate.git", default-features = false }
runtime-io = { package = "sp-io", git = "https://github.com/ProChain/substrate.git", default-features = false }

# inner dependencies
did = { path = "../modules/did", default-features = false }
ads = { path = "../modules/ads", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = "https://github.com/ProChain/substrate.git" }

[dev-dependencies]


[features]
default = ["std"]
std = [
	"authority-discovery-primitives/std",
	"authority-discovery/std",
	"authorship/std",
	"babe-primitives/std",
	"babe/std",
	"balances/std",
	"block-builder-api/std",
	"codec/std",
	"collective/std",
	"contracts-rpc-runtime-api/std",
	"contracts/std",
	"democracy/std",
	"elections-phragmen/std",
	"executive/std",
	"finality-tracker/std",
	"grandpa/std",
	"im-online/std",
	"indices/std",
	"inherents/std",
	"membership/std",
	"nicks/std",
	"node-primitives/std",
	"offchain-primitives/std",
	"offences/std",
	"primitives/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"rustc-hex",
	'runtime-io/std',
	"safe-mix/std",
	"serde/std",
	"session/std",
	"simple-json/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"staking/std",
	"sp-keyring",
	"sp-session/std",
	"sudo/std",
	"support/std",
	"system-rpc-runtime-api/std",
	"system/std",
	"timestamp/std",
	"transaction-payment-rpc-runtime-api/std",
	"transaction-payment/std",
	"treasury/std",
	"sp-transaction-pool/std",
	"utility/std",
	"version/std",
	"did/std",
	"ads/std",
]
