[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "sc-client", git = "https://github.com/ProChain/substrate.git" }
jsonrpc-core = "14.0.3"
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }
sp-runtime = { git = "https://github.com/ProChain/substrate.git" }
pallet-contracts-rpc = { git = "https://github.com/ProChain/substrate.git" }
pallet-transaction-payment-rpc = { git = "https://github.com/ProChain/substrate.git" }
substrate-frame-rpc-system = { path = "../../../utils/frame/rpc/system" }
txpool-api = { package = "sp-transaction-pool-api", git = "https://github.com/ProChain/substrate.git" }
